name: Main
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    uses: DangerN/cogm/.github/workflows/test.yaml@main
  deploy:
    name: Deploy
    uses: DangerN/cogm/.github/workflows/deploy.yaml@main
    with:
      env: prod
    secrets:
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#  test_client:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./client
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 14.x
#      - name: Install Packages
#        run: npm i
#      - name: Build
#        run: npm run build
#      - name: Deploy
#        run: |
#          aws s3 sync ./build s3://${{ secrets.BUCKET_NAME }} --acl public-read --delete
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_EC2_METADATA_DISABLED: true