name: Main
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    uses: DangerN/cogm/.github/workflows/test.yaml@main
  deploy:
    name: Deploy
    uses: DangerN/cogm/.github/workflows/deploy.yaml@main
    needs: test
    with:
      env: prod
    secrets:
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      DOCUMENTS_BUCKET_NAME: ${{ secrets.DOCUMENTS_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
