on: [pull_request, push]
jobs:
  test_client:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Packages
        run: npm i
      - name: Build
        run: npm run build
