on: [pull_request, push]
jobs:
  test_client:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - name: Install Packages
        run: npm i
      - name: Build
        run: npm run build
